#!/usr/bin/env python3
"""Generate the Soundfont Explorer GM diagnostic MIDI (CC0, deterministic).

Layout (120 bpm, 480 ppqn, format 1):

  track 0  tempo/time signature, GM System On sysex (F0 7E 7F 09 01 F7), text
  track 1  all 128 GM programs in order — one 1.0 s phrase each (four
           sixteenths C-E-G-C' then the upper C held for a beat), on rotating
           melodic channels so release tails never collide with the next
           program change; octave per GM family (bass low, piccolo high ...)
  track 2  GM drum map: notes 35..81 on channel 10, one eighth note each
  track 3  pitch-bend and controller tests on a held note:
           bend up/down/return (default +-2 semitone range), CC1 modulation,
           CC7 volume, CC10 pan, CC11 expression, CC64 sustain (staccato notes
           that should ring), CC91 reverb send, CC93 chorus send

Total ~2:50 (170 s) before the canonical 3 s tail.  No randomness anywhere, so the
output bytes are reproducible (sha256 is recorded in songs.json).

    make_diagnostic.py [out.mid]      (default: prints nothing, used by canon.py)
"""
from __future__ import annotations

import os
import sys
from typing import List

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import smf as S  # noqa: E402

PPQ = 480
TEMPO_US = 500000          # 120 bpm -> 1 beat = 0.5 s
BEAT = PPQ
SIXTEENTH = PPQ // 4
EIGHTH = PPQ // 2
VEL = 100

GM_SYSTEM_ON = bytes([0x7E, 0x7F, 0x09, 0x01, 0xF7])

# base note (the "C") per GM family of 8 programs
FAMILY_BASE = {
    0: 60,   # piano
    1: 60,   # chromatic percussion
    2: 60,   # organ
    3: 52,   # guitar
    4: 40,   # bass
    5: 60,   # strings
    6: 60,   # ensemble
    7: 60,   # brass
    8: 60,   # reed
    9: 72,   # pipe
    10: 60,  # synth lead
    11: 60,  # synth pad
    12: 60,  # synth fx
    13: 60,  # ethnic
    14: 60,  # percussive
    15: 60,  # sound fx
}
MELODIC_CHANNELS = [c for c in range(16) if c != 9]   # 0-based; 9 == channel 10 (drums)


def ev(tick: int, status: int, *data: int) -> S.Event:
    return S.Event(tick, "channel", status, bytes(data))


def meta(tick: int, mtype: int, data: bytes) -> S.Event:
    return S.Event(tick, "meta", 0xFF, data, mtype)


def text(tick: int, s: str) -> S.Event:
    return meta(tick, 0x01, s.encode("ascii"))


def marker(tick: int, s: str) -> S.Event:
    return meta(tick, 0x06, s.encode("ascii"))


def phrase(track: List[S.Event], tick: int, ch: int, base: int, vel: int = VEL) -> int:
    """C E G C' sixteenths then C' held one beat.  Returns the next free tick."""
    for i, off in enumerate((0, 4, 7, 12)):
        t = tick + i * SIXTEENTH
        track.append(ev(t, 0x90 | ch, base + off, vel))
        track.append(ev(t + SIXTEENTH - 10, 0x80 | ch, base + off, 0))
    t = tick + 4 * SIXTEENTH
    track.append(ev(t, 0x90 | ch, base + 12, vel))
    track.append(ev(t + BEAT - 10, 0x80 | ch, base + 12, 0))
    return tick + 2 * BEAT


def build() -> S.Smf:
    smf = S.Smf(1, PPQ, [[], [], [], []])
    t0, programs, drums, ctl = smf.tracks

    # --- track 0: conductor ------------------------------------------------
    t0.append(meta(0, 0x03, b"Soundfont Explorer GM diagnostic"))
    t0.append(text(0, "Soundfont Explorer GM diagnostic - CC0 1.0 - generated by songs/tools/make_diagnostic.py"))
    t0.append(meta(0, 0x58, bytes([4, 2, 24, 8])))
    t0.append(meta(0, 0x51, TEMPO_US.to_bytes(3, "big")))
    t0.append(S.Event(0, "sysex", 0xF0, GM_SYSTEM_ON))

    # --- track 1: 128 programs --------------------------------------------
    programs.append(meta(0, 0x03, b"GM programs 1-128"))
    tick = BEAT  # leave one beat after the GM reset
    for prog in range(128):
        ch = MELODIC_CHANNELS[prog % len(MELODIC_CHANNELS)]
        if prog % 8 == 0:
            t0.append(marker(tick, "programs %d-%d" % (prog + 1, prog + 8)))
        # reset the channel's state before reusing it
        programs.append(ev(tick, 0xB0 | ch, 7, 100))     # volume
        programs.append(ev(tick, 0xB0 | ch, 10, 64))     # pan
        programs.append(ev(tick, 0xB0 | ch, 11, 127))    # expression
        programs.append(ev(tick, 0xC0 | ch, prog))
        tick = phrase(programs, tick, ch, FAMILY_BASE[prog // 8])
    prog_end = tick  # 1 + 256 beats

    # --- track 2: drum map -------------------------------------------------
    drums.append(meta(0, 0x03, b"GM drum map 35-81 (channel 10)"))
    tick = prog_end + BEAT
    t0.append(marker(tick, "drums 35-81"))
    drums.append(ev(tick, 0xB0 | 9, 7, 100))
    drums.append(ev(tick, 0xB0 | 9, 10, 64))
    drums.append(ev(tick, 0xC0 | 9, 0))      # standard kit
    for note in range(35, 82):
        drums.append(ev(tick, 0x99, note, 110))
        drums.append(ev(tick + EIGHTH - 10, 0x89, note, 0))
        tick += EIGHTH
    tick += BEAT
    drum_end = tick

    # --- track 3: bends and controllers -----------------------------------
    ctl.append(meta(0, 0x03, b"pitch bend + CC1/7/10/11/64/91/93"))
    ch = 0
    tick = drum_end + BEAT

    def hold(note: int, start: int, length: int, program: int) -> None:
        ctl.append(ev(start, 0xC0 | ch, program))
        ctl.append(ev(start, 0xB0 | ch, 7, 100))
        ctl.append(ev(start, 0xB0 | ch, 10, 64))
        ctl.append(ev(start, 0xB0 | ch, 11, 127))
        ctl.append(ev(start, 0xB0 | ch, 1, 0))
        ctl.append(ev(start, 0xB0 | ch, 91, 0))
        ctl.append(ev(start, 0xB0 | ch, 93, 0))
        ctl.append(ev(start, 0xE0 | ch, 0, 64))  # bend centre
        ctl.append(ev(start, 0x90 | ch, note, VEL))
        ctl.append(ev(start + length - 10, 0x80 | ch, note, 0))

    def ramp_cc(cc: int, start: int, length: int, v0: int, v1: int, steps: int = 32) -> None:
        for i in range(steps + 1):
            v = round(v0 + (v1 - v0) * i / steps)
            ctl.append(ev(start + length * i // steps, 0xB0 | ch, cc, v))

    def ramp_bend(start: int, length: int, b0: int, b1: int, steps: int = 48) -> None:
        for i in range(steps + 1):
            b = round(b0 + (b1 - b0) * i / steps) + 8192
            b = max(0, min(16383, b))
            ctl.append(ev(start + length * i // steps, 0xE0 | ch, b & 0x7F, b >> 7))

    # pitch bend: saw lead, 4 s: up a whole tone, down two, back to centre
    t0.append(marker(tick, "pitch bend +8191/-8192"))
    hold(64, tick, 8 * BEAT, 81)
    ramp_bend(tick, 2 * BEAT, 0, 8191)
    ramp_bend(tick + 2 * BEAT, 4 * BEAT, 8191, -8192)
    ramp_bend(tick + 6 * BEAT, 2 * BEAT, -8192, 0)
    tick += 9 * BEAT

    # CC1 modulation on strings, 3 s: 0 -> 127 -> 0
    t0.append(marker(tick, "CC1 modulation"))
    hold(67, tick, 6 * BEAT, 48)
    ramp_cc(1, tick, 3 * BEAT, 0, 127)
    ramp_cc(1, tick + 3 * BEAT, 3 * BEAT, 127, 0)
    tick += 7 * BEAT

    # CC7 volume on organ: 127 -> 0 -> 127
    t0.append(marker(tick, "CC7 volume"))
    hold(60, tick, 6 * BEAT, 16)
    ramp_cc(7, tick, 3 * BEAT, 127, 0)
    ramp_cc(7, tick + 3 * BEAT, 3 * BEAT, 0, 127)
    tick += 7 * BEAT

    # CC10 pan on a synth pad: left -> right -> centre
    t0.append(marker(tick, "CC10 pan"))
    hold(62, tick, 6 * BEAT, 88)
    ramp_cc(10, tick, 3 * BEAT, 0, 127)
    ramp_cc(10, tick + 3 * BEAT, 3 * BEAT, 127, 64)
    tick += 7 * BEAT

    # CC11 expression on brass: 127 -> 0 -> 127
    t0.append(marker(tick, "CC11 expression"))
    hold(62, tick, 6 * BEAT, 61)
    ramp_cc(11, tick, 3 * BEAT, 127, 0)
    ramp_cc(11, tick + 3 * BEAT, 3 * BEAT, 0, 127)
    tick += 7 * BEAT

    # CC64 sustain on piano: staccato arpeggio with pedal down, then pedal up
    t0.append(marker(tick, "CC64 sustain"))
    ctl.append(ev(tick, 0xC0 | ch, 0))
    ctl.append(ev(tick, 0xB0 | ch, 7, 100))
    ctl.append(ev(tick, 0xB0 | ch, 11, 127))
    ctl.append(ev(tick, 0xB0 | ch, 10, 64))
    ctl.append(ev(tick, 0xB0 | ch, 64, 127))
    for i, n in enumerate((48, 55, 60, 64, 67, 72, 76, 79)):
        t = tick + i * SIXTEENTH
        ctl.append(ev(t, 0x90 | ch, n, VEL))
        ctl.append(ev(t + SIXTEENTH // 2, 0x80 | ch, n, 0))
    ctl.append(ev(tick + 4 * BEAT, 0xB0 | ch, 64, 0))   # pedal up: everything stops
    tick += 6 * BEAT

    # CC91 reverb send on a bell: 0 -> 127 (renders have reverb off; documents the control)
    t0.append(marker(tick, "CC91 reverb send"))
    hold(72, tick, 6 * BEAT, 14)
    ramp_cc(91, tick, 6 * BEAT, 0, 127)
    tick += 7 * BEAT

    # CC93 chorus send on an electric piano: 0 -> 127
    t0.append(marker(tick, "CC93 chorus send"))
    hold(64, tick, 6 * BEAT, 4)
    ramp_cc(93, tick, 6 * BEAT, 0, 127)
    tick += 6 * BEAT

    # all notes off / reset controllers on every channel as a tidy end
    for c in range(16):
        ctl.append(ev(tick, 0xB0 | c, 121, 0))
        ctl.append(ev(tick, 0xB0 | c, 123, 0))
    t0.append(marker(tick, "end"))
    return smf


def main(argv: List[str]) -> int:
    smf = build()
    if len(argv) > 1:
        S.save(smf, argv[1])
        print("wrote %s: %d events, %.1f s" % (argv[1], sum(len(t) for t in smf.tracks), S.midi_end_seconds(smf)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
